US-2.1 Created scaffold UserRoles and used Rubocop
itechart-warehouse/Warehouse-itechart pull request #4
Opened 2022-01-27 23:45 UTC by Lonely-fr

Used rubocop command and created model with migration. Need meet for UserRoles names and style.

2022-01-28 04:44 UTC, Laranto-spb commented
We need Rspec for controller

2022-01-28 04:46 UTC, Laranto-spb requested changes
I think we need rspecs because of Model and Controller

2022-01-29 10:18 UTC, Laranto-spb commented on db/migrate/20220128115728_create_default_users_role.rb
> +end
Can you rename method like predefine_roles or create_general_roles or whatever. Just for clear naming)

2022-01-30 06:12 UTC, Laranto-spb approved these changes

2022-01-30 14:20 UTC, alllpim approved these changes

2022-01-30 14:23 UTC, StoreCarCharIsInNoSave approved these changes

2022-01-30 14:25 UTC, merged